insert into Category (CategoryName) values ('FOOD - BEVERAGES#10');
insert into Category (CategoryName) values ('FOOD - BAKING & COOKING#75');
insert into Category (CategoryName) values ('FOOD - BAKERY#223');
insert into Category (CategoryName) values ('FOOD - PREPARED FOODS#670');
insert into Category (CategoryName) values ('FOOD - SAUCES#636');
insert into Category (CategoryName) values ('ACCESSORIES#528');
insert into Category (CategoryName) values ('FOOD - FREEZER#935');
insert into Category (CategoryName) values ('FOOD - SAUCES#420');
insert into Category (CategoryName) values ('FOOD - PRODUCE#320');
insert into Category (CategoryName) values ('CLOTHING - OUTERWEAR#95');
insert into Category (CategoryName) values ('FOOD - DAIRY#378');
insert into Category (CategoryName) values ('FOOD - CANNED GOODS#243');
insert into Category (CategoryName) values ('FOOD - BEVERAGES#624');
insert into Category (CategoryName) values ('FOOD - SNACKS#515');
insert into Category (CategoryName) values ('OFFICE#441');
insert into Category (CategoryName) values ('FOOD - PRODUCE#44');
insert into Category (CategoryName) values ('FOOD - SPICES#681');
insert into Category (CategoryName) values ('KITCHEN#51');
insert into Category (CategoryName) values ('FOOD - FROZEN FOODS#568');
insert into Category (CategoryName) values ('FOOD - CONDIMENTS#870');
insert into Category (CategoryName) values ('CLOTHING#367');
insert into Category (CategoryName) values ('AUDIO#619');
insert into Category (CategoryName) values ('PHOTOGRAPHY#832');
insert into Category (CategoryName) values ('FOOD - SAUCES#395');
insert into Category (CategoryName) values ('FOOD - PRODUCE#133');
insert into Category (CategoryName) values ('GROOMING#386');
insert into Category (CategoryName) values ('FOOD - DIPS#8');
insert into Category (CategoryName) values ('GARDEN#239');
insert into Category (CategoryName) values ('KITCHEN#140');
insert into Category (CategoryName) values ('TOYS#193');
insert into Category (CategoryName) values ('OUTDOOR#989');
insert into Category (CategoryName) values ('CLOTHING - OUTERWEAR#576');
insert into Category (CategoryName) values ('TOYS#639');
insert into Category (CategoryName) values ('FOOD - BAKERY#912');
insert into Category (CategoryName) values ('ELECTRONICS#2');
insert into Category (CategoryName) values ('FOOD - SAUCES#184');
insert into Category (CategoryName) values ('FOOD - PREPARED MEALS#399');
insert into Category (CategoryName) values ('FOOD - SALADS#347');
insert into Category (CategoryName) values ('FOOD - PREPARED FOODS#585');
insert into Category (CategoryName) values ('OFFICE#284');
insert into Category (CategoryName) values ('HOME#90');
insert into Category (CategoryName) values ('FOOD - CONDIMENTS#590');
insert into Category (CategoryName) values ('FOOD - MEAT & SEAFOOD#602');
insert into Category (CategoryName) values ('HOME#954');
insert into Category (CategoryName) values ('FOOD - BEVERAGES#516');
insert into Category (CategoryName) values ('FOOD - SNACKS#758');
insert into Category (CategoryName) values ('ACCESSORIES#560');
insert into Category (CategoryName) values ('BEAUTY#584');
insert into Category (CategoryName) values ('FOOD - CONDIMENTS#317');
insert into Category (CategoryName) values ('FOOD - SPICES#189');
insert into Category (CategoryName) values ('FOOD - BEVERAGES#952');
insert into Category (CategoryName) values ('HOME#985');
insert into Category (CategoryName) values ('HOME APPLIANCES#871');
insert into Category (CategoryName) values ('FOOD - MEAT#329');
insert into Category (CategoryName) values ('ART SUPPLIES#864');
insert into Category (CategoryName) values ('FOOD - FROZEN MEALS#531');
insert into Category (CategoryName) values ('FOOD - CONDIMENTS#773');
insert into Category (CategoryName) values ('FOOD - SOUPS#232');
insert into Category (CategoryName) values ('GARDEN#645');
insert into Category (CategoryName) values ('FOOD - BAKED GOODS#350');
insert into Category (CategoryName) values ('HOME#385');
insert into Category (CategoryName) values ('FOOD - OILS & VINEGARS#427');
insert into Category (CategoryName) values ('FOOD - SIDES#805');
insert into Category (CategoryName) values ('OUTDOOR#961');
insert into Category (CategoryName) values ('ACCESSORIES#667');
insert into Category (CategoryName) values ('GARDEN#413');
insert into Category (CategoryName) values ('FOOD - PRODUCE#728');
insert into Category (CategoryName) values ('FOOD - CANNED GOODS#10');
insert into Category (CategoryName) values ('FITNESS#56');
insert into Category (CategoryName) values ('FOOD - CANNED GOODS#535');
insert into Category (CategoryName) values ('HOME#552');
insert into Category (CategoryName) values ('FITNESS#32');
insert into Category (CategoryName) values ('TOYS#66');
insert into Category (CategoryName) values ('TOOLS#715');
insert into Category (CategoryName) values ('HOME#856');
insert into Category (CategoryName) values ('FOOD - BAKING & COOKING#214');
insert into Category (CategoryName) values ('FOOD - CONDIMENTS#983');
insert into Category (CategoryName) values ('GARDEN#416');
insert into Category (CategoryName) values ('TOYS#747');
insert into Category (CategoryName) values ('PETS#6');
insert into Category (CategoryName) values ('FOOD - MEATS#202');
insert into Category (CategoryName) values ('FOOD - SNACKS#48');
insert into Category (CategoryName) values ('ELECTRONICS#892');
insert into Category (CategoryName) values ('KITCHEN#185');
insert into Category (CategoryName) values ('HOME#20');
insert into Category (CategoryName) values ('FOOD - FROZEN FOODS#382');
insert into Category (CategoryName) values ('ELECTRONICS#977');
insert into Category (CategoryName) values ('FOOD - SNACKS#425');
insert into Category (CategoryName) values ('FOOD - BAKING#712');
insert into Category (CategoryName) values ('FITNESS#368');
insert into Category (CategoryName) values ('FOOD - BREAKFAST#397');
insert into Category (CategoryName) values ('KITCHEN#852');
insert into Category (CategoryName) values ('TRAVEL#758');
insert into Category (CategoryName) values ('SAFETY#578');
insert into Category (CategoryName) values ('HOME#611');
insert into Category (CategoryName) values ('TOYS#182');
insert into Category (CategoryName) values ('FOOD - SNACKS#413');
insert into Category (CategoryName) values ('FOOD - SNACKS#660');
insert into Category (CategoryName) values ('FOOD - BEVERAGES#297');
insert into Category (CategoryName) values ('FOOD - VEGETABLES#537');
insert into Category (CategoryName) values ('TOYS#259');
insert into Category (CategoryName) values ('FOOD - BAKED GOODS#118');
insert into Category (CategoryName) values ('FOOD - GRAINS#162');
insert into Category (CategoryName) values ('FOOD - CONDIMENTS#642');
insert into Category (CategoryName) values ('AUDIO#806');
insert into Category (CategoryName) values ('FOOD - SNACKS#757');
insert into Category (CategoryName) values ('KITCHEN#536');
insert into Category (CategoryName) values ('FOOD - PRODUCE#911');
insert into Category (CategoryName) values ('FOOD - BAKED GOODS#11');
insert into Category (CategoryName) values ('TRAVEL#327');
insert into Category (CategoryName) values ('FOOD - FRUITS#990');
insert into Category (CategoryName) values ('PETS#766');
insert into Category (CategoryName) values ('FOOD - CANNED GOODS#730');
insert into Category (CategoryName) values ('FOOD - CANNED GOODS#169');
insert into Category (CategoryName) values ('FOOD - PANTRY#805');
insert into Category (CategoryName) values ('OFFICE#311');
insert into Category (CategoryName) values ('FOOD - CONDIMENTS#807');
insert into Category (CategoryName) values ('FOOD - BAKERY#450');
insert into Category (CategoryName) values ('OUTDOOR#865');
insert into Category (CategoryName) values ('FOOD - MARINADES#60');
insert into Category (CategoryName) values ('FITNESS#389');
insert into Category (CategoryName) values ('KITCHEN#413');
insert into Category (CategoryName) values ('FOOD - BEVERAGES#502');
insert into Category (CategoryName) values ('FOOD - VEGETABLES#503');
insert into Category (CategoryName) values ('KITCHEN#37');
insert into Category (CategoryName) values ('FOOD - FREEZER#686');
insert into Category (CategoryName) values ('OUTDOOR#96');
insert into Category (CategoryName) values ('CLOTHING - OUTERWEAR#200');
insert into Category (CategoryName) values ('FOOD - DAIRY ALTERNATIVES#86');
insert into Category (CategoryName) values ('PETS#289');
insert into Category (CategoryName) values ('FOOD - MEAT#45');
insert into Category (CategoryName) values ('FOOD - PREPARED FOODS#995');
insert into Category (CategoryName) values ('FOOD - SNACKS#528');
insert into Category (CategoryName) values ('ACCESSORIES#644');
insert into Category (CategoryName) values ('FOOD - PRODUCE#492');
insert into Category (CategoryName) values ('FOOD - BREAKFAST#800');
insert into Category (CategoryName) values ('HOME#754');
insert into Category (CategoryName) values ('FOOD - BREAKFAST#526');
insert into Category (CategoryName) values ('FOOD - FROZEN FOODS#271');
insert into Category (CategoryName) values ('FOOD - SNACKS#634');
insert into Category (CategoryName) values ('OUTDOOR#432');
insert into Category (CategoryName) values ('AUDIO#566');
insert into Category (CategoryName) values ('HOME#113');
insert into Category (CategoryName) values ('AUDIO#591');
insert into Category (CategoryName) values ('FOOD - SNACKS#689');
insert into Category (CategoryName) values ('PETS#421');
insert into Category (CategoryName) values ('KITCHEN#402');
insert into Category (CategoryName) values ('OUTDOOR#743');
insert into Category (CategoryName) values ('FITNESS#739');
insert into Category (CategoryName) values ('FOOD - VEGETABLES#471');
insert into Category (CategoryName) values ('FOOD - PRODUCE#722');
insert into Category (CategoryName) values ('KITCHEN#539');
insert into Category (CategoryName) values ('FOOD - SNACKS#315');
insert into Category (CategoryName) values ('KITCHEN#91');
insert into Category (CategoryName) values ('FOOD - MEAT#264');
insert into Category (CategoryName) values ('HOME#271');
insert into Category (CategoryName) values ('KITCHEN#202');
insert into Category (CategoryName) values ('CLOTHING - OUTERWEAR#152');
insert into Category (CategoryName) values ('PETS#436');
insert into Category (CategoryName) values ('FOOD - CONDIMENTS#229');
insert into Category (CategoryName) values ('AUDIO#544');
insert into Category (CategoryName) values ('OFFICE#816');
insert into Category (CategoryName) values ('FOOD - CONDIMENTS#36');
insert into Category (CategoryName) values ('FOOD - SPICES#420');
insert into Category (CategoryName) values ('OUTDOOR#937');
insert into Category (CategoryName) values ('CLOTHING - SHOES#810');
insert into Category (CategoryName) values ('FOOD - DAIRY#978');
insert into Category (CategoryName) values ('CLOTHING - OUTERWEAR#766');
insert into Category (CategoryName) values ('FOOD - PRODUCE#201');
insert into Category (CategoryName) values ('FOOD - FRESH PRODUCE#760');
insert into Category (CategoryName) values ('FOOD - MEATS#308');
insert into Category (CategoryName) values ('ACCESSORIES#388');
insert into Category (CategoryName) values ('FOOD - MEAL KITS#227');
insert into Category (CategoryName) values ('FOOD - PRODUCE#617');
insert into Category (CategoryName) values ('KITCHEN#670');
insert into Category (CategoryName) values ('FOOD - FROZEN FOODS#402');
insert into Category (CategoryName) values ('FOOD - PREPARED MEALS#404');
insert into Category (CategoryName) values ('OUTDOOR#4');
insert into Category (CategoryName) values ('AUTOMOTIVE#63');
insert into Category (CategoryName) values ('FOOD - CONDIMENTS#320');
insert into Category (CategoryName) values ('GAMING#270');
insert into Category (CategoryName) values ('FOOD - SPICES#715');
insert into Category (CategoryName) values ('PETS#479');
insert into Category (CategoryName) values ('CLOTHING - ACCESSORIES#585');
insert into Category (CategoryName) values ('FOOD - FROZEN#35');
insert into Category (CategoryName) values ('FOOD - FROZEN FOODS#71');
insert into Category (CategoryName) values ('FITNESS#28');
insert into Category (CategoryName) values ('HOME#871');
insert into Category (CategoryName) values ('FOOD - BEVERAGES#274');
insert into Category (CategoryName) values ('FOOD - SALADS#73');
insert into Category (CategoryName) values ('FOOD - FROZEN MEALS#730');
insert into Category (CategoryName) values ('PETS#475');
insert into Category (CategoryName) values ('KITCHEN#124');
insert into Category (CategoryName) values ('FOOD - BEVERAGES#527');
insert into Category (CategoryName) values ('FOOD - PREPARED FOODS#219');
insert into Category (CategoryName) values ('CLOTHING#164');
insert into Category (CategoryName) values ('PETS#543');
insert into Category (CategoryName) values ('HOME#955');
insert into Category (CategoryName) values ('FOOD - FROZEN FOODS#306');
insert into Category (CategoryName) values ('KITCHEN#377');
insert into Category (CategoryName) values ('CLOTHING - BOTTOMS#882');
insert into Category (CategoryName) values ('FOOD - MEAT#422');
insert into Category (CategoryName) values ('KITCHEN#832');
insert into Category (CategoryName) values ('OUTDOOR#679');
insert into Category (CategoryName) values ('FOOD - SNACKS#87');
insert into Category (CategoryName) values ('CLOTHING - SHIRTS#104');
insert into Category (CategoryName) values ('KITCHEN#329');
insert into Category (CategoryName) values ('FITNESS#898');
insert into Category (CategoryName) values ('OUTDOOR#51');
insert into Category (CategoryName) values ('CLOTHING - DRESSES#198');
insert into Category (CategoryName) values ('TOYS#396');
insert into Category (CategoryName) values ('FOOD - SAUCES#404');
insert into Category (CategoryName) values ('FOOD - BAKING & COOKING#2');
insert into Category (CategoryName) values ('FOOD - SNACKS#191');
insert into Category (CategoryName) values ('ELECTRONICS#625');
insert into Category (CategoryName) values ('FOOD - SOUPS#105');
insert into Category (CategoryName) values ('FOOD - SNACKS#844');
insert into Category (CategoryName) values ('FOOD - BEVERAGES#89');
insert into Category (CategoryName) values ('SMART HOME#250');
insert into Category (CategoryName) values ('FOOD - FROZEN FOOD#68');
insert into Category (CategoryName) values ('FOOD - CONDIMENTS#553');
insert into Category (CategoryName) values ('FOOD - CANNED GOODS#188');
insert into Category (CategoryName) values ('WEARABLE TECH#622');
insert into Category (CategoryName) values ('FOOD - MEAT#191');
insert into Category (CategoryName) values ('HOME#26');
insert into Category (CategoryName) values ('HOME#597');
insert into Category (CategoryName) values ('KITCHEN#850');
insert into Category (CategoryName) values ('ELECTRONICS#77');
insert into Category (CategoryName) values ('CLOTHING - FOOTWEAR#329');
insert into Category (CategoryName) values ('FITNESS#36');
insert into Category (CategoryName) values ('PETS#92');
insert into Category (CategoryName) values ('HOME#251');
insert into Category (CategoryName) values ('PHOTOGRAPHY#922');
insert into Category (CategoryName) values ('HOME#389');
insert into Category (CategoryName) values ('TOOLS#962');
insert into Category (CategoryName) values ('COMPUTERS#854');
insert into Category (CategoryName) values ('HOME#274');
insert into Category (CategoryName) values ('FOOD - NUTS#122');
insert into Category (CategoryName) values ('OUTDOOR#386');
insert into Category (CategoryName) values ('FOOD - MEATS#862');
insert into Category (CategoryName) values ('FOOD - CONDIMENTS#462');
insert into Category (CategoryName) values ('FOOD - PREPARED FOODS#696');
insert into Category (CategoryName) values ('ACCESSORIES#29');
insert into Category (CategoryName) values ('FOOD - FROZEN FOODS#905');
insert into Category (CategoryName) values ('PETS#668');
insert into Category (CategoryName) values ('TOYS#603');
insert into Category (CategoryName) values ('OUTDOOR#666');
insert into Category (CategoryName) values ('HEALTH#782');
insert into Category (CategoryName) values ('FOOD - SNACKS#657');
insert into Category (CategoryName) values ('FOOD - SNACKS#79');
insert into Category (CategoryName) values ('CLOTHING - JUMPSUITS#460');
insert into Category (CategoryName) values ('FOOD - SPICES#155');
insert into Category (CategoryName) values ('FOOD - MEAT#9');
insert into Category (CategoryName) values ('FOOD - CONDIMENTS#446');
insert into Category (CategoryName) values ('CLOTHING - ACCESSORIES#744');
insert into Category (CategoryName) values ('KITCHEN#710');
insert into Category (CategoryName) values ('FOOD - SNACKS#602');
insert into Category (CategoryName) values ('FOOD - SNACKS#401');
insert into Category (CategoryName) values ('FOOD - GRAINS#599');
insert into Category (CategoryName) values ('KITCHEN#616');
insert into Category (CategoryName) values ('GARDEN#120');
insert into Category (CategoryName) values ('HEALTH#54');
insert into Category (CategoryName) values ('FOOD - SNACKS#598');
insert into Category (CategoryName) values ('FOOD - DELI#859');
insert into Category (CategoryName) values ('FOOD - FROZEN FOODS#776');
insert into Category (CategoryName) values ('FOOD - PRODUCE#781');
insert into Category (CategoryName) values ('AUDIO#273');
insert into Category (CategoryName) values ('FITNESS#647');
insert into Category (CategoryName) values ('TRAVEL#307');
insert into Category (CategoryName) values ('FOOD - SNACKS#525');
insert into Category (CategoryName) values ('FOOD - DAIRY ALTERNATIVES#845');
insert into Category (CategoryName) values ('CLOTHING - ACTIVEWEAR#999');
insert into Category (CategoryName) values ('TOOLS#541');
insert into Category (CategoryName) values ('CLOTHING - BOTTOMS#370');
insert into Category (CategoryName) values ('HEALTH#948');
insert into Category (CategoryName) values ('OFFICE#492');
insert into Category (CategoryName) values ('KITCHEN#847');
insert into Category (CategoryName) values ('FITNESS#67');
insert into Category (CategoryName) values ('FOOD - SNACKS#966');
insert into Category (CategoryName) values ('KITCHEN#132');
insert into Category (CategoryName) values ('HOME#222');
insert into Category (CategoryName) values ('KITCHEN#53');
insert into Category (CategoryName) values ('OUTDOOR#389');
insert into Category (CategoryName) values ('FOOD - BREAKFAST#825');
insert into Category (CategoryName) values ('ELECTRONICS#672');
insert into Category (CategoryName) values ('KITCHEN#723');
insert into Category (CategoryName) values ('CLOTHING - SHOES#588');
insert into Category (CategoryName) values ('OFFICE#259');
insert into Category (CategoryName) values ('FOOD - FRUITS#953');
insert into Category (CategoryName) values ('HOME#561');
insert into Category (CategoryName) values ('OUTDOOR#852');
insert into Category (CategoryName) values ('CLOTHING - OUTERWEAR#890');
insert into Category (CategoryName) values ('GARDEN#107');
insert into Category (CategoryName) values ('FOOD - DAIRY#869');
insert into Category (CategoryName) values ('TOYS#922');
insert into Category (CategoryName) values ('OFFICE#818');
insert into Category (CategoryName) values ('OUTDOOR#957');
insert into Category (CategoryName) values ('CLOTHING - ACCESSORIES#941');
insert into Category (CategoryName) values ('FOOD - BREAKFAST FOODS#649');
insert into Category (CategoryName) values ('KITCHEN#364');
insert into Category (CategoryName) values ('COMPUTERS#471');
insert into Category (CategoryName) values ('HEALTH#936');
insert into Category (CategoryName) values ('HEALTH#237');
insert into Category (CategoryName) values ('KITCHEN#312');
insert into Category (CategoryName) values ('FOOD - SNACKS#608');
insert into Category (CategoryName) values ('FOOD - HEALTH FOODS#494');
insert into Category (CategoryName) values ('FOOD - FROZEN DESSERTS#793');
insert into Category (CategoryName) values ('TOYS#132');
insert into Category (CategoryName) values ('KITCHEN#97');
insert into Category (CategoryName) values ('FOOD - COOKING OILS#162');
insert into Category (CategoryName) values ('GARDEN#146');
insert into Category (CategoryName) values ('FOOD - BREAKFAST#495');
insert into Category (CategoryName) values ('CLOTHING - TOPS#253');
insert into Category (CategoryName) values ('CLOTHING - JUMPSUITS#556');
insert into Category (CategoryName) values ('HOME#737');
insert into Category (CategoryName) values ('KITCHEN#6');
insert into Category (CategoryName) values ('FOOD - MEAL KITS#957');
insert into Category (CategoryName) values ('FOOD - SALADS#189');
insert into Category (CategoryName) values ('FITNESS#609');
insert into Category (CategoryName) values ('FOOD - FROZEN MEALS#90');
insert into Category (CategoryName) values ('KITCHEN#385');
insert into Category (CategoryName) values ('KITCHEN#872');
insert into Category (CategoryName) values ('GARDEN#100');
insert into Category (CategoryName) values ('FOOD - SPICES#387');
insert into Category (CategoryName) values ('FITNESS#379');
insert into Category (CategoryName) values ('FOOD - CONDIMENTS#43');
insert into Category (CategoryName) values ('FOOD - GRAINS#115');
insert into Category (CategoryName) values ('PHOTOGRAPHY#569');
insert into Category (CategoryName) values ('FOOD - SNACKS#277');
insert into Category (CategoryName) values ('FOOD - SALADS#807');
insert into Category (CategoryName) values ('FITNESS#830');
insert into Category (CategoryName) values ('FOOD - CONDIMENTS#457');
insert into Category (CategoryName) values ('CLOTHING - ACCESSORIES#649');
insert into Category (CategoryName) values ('FOOD - FROZEN FOODS#883');
insert into Category (CategoryName) values ('FOOD - FROZEN FOODS#122');
insert into Category (CategoryName) values ('KITCHEN#334');
insert into Category (CategoryName) values ('FOOD - SNACKS#92');
insert into Category (CategoryName) values ('KITCHEN#811');
insert into Category (CategoryName) values ('KITCHEN#654');
insert into Category (CategoryName) values ('FOOD - PRODUCE#826');
insert into Category (CategoryName) values ('KITCHEN#9');
insert into Category (CategoryName) values ('FOOD - SNACKS#116');
insert into Category (CategoryName) values ('FOOD - SALADS#694');
insert into Category (CategoryName) values ('ACCESSORIES#198');
insert into Category (CategoryName) values ('FITNESS#416');
insert into Category (CategoryName) values ('HOME#232');
insert into Category (CategoryName) values ('FOOD - FROZEN FOODS#538');
insert into Category (CategoryName) values ('FOOD - FROZEN FOODS#894');
insert into Category (CategoryName) values ('FITNESS#346');
insert into Category (CategoryName) values ('FOOD - BAKERY#838');
insert into Category (CategoryName) values ('FOOD - FROZEN MEALS#918');
insert into Category (CategoryName) values ('FOOD - PASTA#958');
insert into Category (CategoryName) values ('FOOD - BAKERY#391');
insert into Category (CategoryName) values ('FOOD - PASTA#743');
insert into Category (CategoryName) values ('FOOD - CONDIMENTS#88');
insert into Category (CategoryName) values ('FOOD - COOKING OIL#575');
insert into Category (CategoryName) values ('FOOD - SPICES#285');
insert into Category (CategoryName) values ('KITCHEN#120');
insert into Category (CategoryName) values ('FOOD - SNACKS#357');
insert into Category (CategoryName) values ('AUDIO#417');
insert into Category (CategoryName) values ('FOOD - CONDIMENTS#661');
insert into Category (CategoryName) values ('AUTOMOTIVE#52');
insert into Category (CategoryName) values ('OUTDOOR#644');
insert into Category (CategoryName) values ('AUTOMOTIVE#720');
insert into Category (CategoryName) values ('KITCHEN#315');
insert into Category (CategoryName) values ('FOOD - SEASONINGS#525');
insert into Category (CategoryName) values ('OUTDOOR#899');
insert into Category (CategoryName) values ('FOOD - BEVERAGES#911');
insert into Category (CategoryName) values ('OUTDOOR#789');
insert into Category (CategoryName) values ('KITCHEN#828');
insert into Category (CategoryName) values ('CLOTHING - BOTTOMS#66');
insert into Category (CategoryName) values ('FOOD - SNACKS#211');
insert into Category (CategoryName) values ('HOME#229');
insert into Category (CategoryName) values ('MUSIC#571');
insert into Category (CategoryName) values ('ACCESSORIES#174');
insert into Category (CategoryName) values ('FOOD - CONDIMENTS#484');
insert into Category (CategoryName) values ('FOOD - BREAKFAST FOODS#367');
insert into Category (CategoryName) values ('TOYS#819');
insert into Category (CategoryName) values ('FOOD - CONDIMENTS#473');
insert into Category (CategoryName) values ('FOOD - SNACKS#166');
insert into Category (CategoryName) values ('ACCESSORIES#411');
insert into Category (CategoryName) values ('FOOD - SALADS#66');
insert into Category (CategoryName) values ('OUTDOOR#10');
insert into Category (CategoryName) values ('FOOD - DIPS#463');
insert into Category (CategoryName) values ('FOOD - VEGETABLES#716');
insert into Category (CategoryName) values ('GARDEN#327');
insert into Category (CategoryName) values ('FOOD - SOUPS#653');
insert into Category (CategoryName) values ('KITCHEN#232');
insert into Category (CategoryName) values ('OFFICE#618');
insert into Category (CategoryName) values ('FOOD - SPICES#636');
insert into Category (CategoryName) values ('FOOD - BAKERY#375');
insert into Category (CategoryName) values ('FOOD - BAKING GOODS#631');
insert into Category (CategoryName) values ('FOOD - BEVERAGES#51');
insert into Category (CategoryName) values ('ELECTRONICS#869');
insert into Category (CategoryName) values ('ELECTRONICS#714');
insert into Category (CategoryName) values ('FOOD - FROZEN MEALS#391');
insert into Category (CategoryName) values ('FOOD - PRODUCE#997');
insert into Category (CategoryName) values ('KITCHEN#420');
insert into Category (CategoryName) values ('FOOD - GRAINS#770');
insert into Category (CategoryName) values ('FOOD - BAKING#276');
insert into Category (CategoryName) values ('KITCHEN#237');
insert into Category (CategoryName) values ('FOOD - FROZEN VEGETABLES#301');
insert into Category (CategoryName) values ('ACCESSORIES#840');
insert into Category (CategoryName) values ('FOOD - GRAINS#90');
insert into Category (CategoryName) values ('FOOD - FROZEN FOODS#221');
insert into Category (CategoryName) values ('HOME#228');
insert into Category (CategoryName) values ('FOOD - BAKING#377');
insert into Category (CategoryName) values ('FOOD - MEAT ALTERNATIVES#844');
insert into Category (CategoryName) values ('FOOD - CONDIMENTS#588');
insert into Category (CategoryName) values ('ELECTRONICS#882');
insert into Category (CategoryName) values ('FOOD - MEAL KITS#391');
insert into Category (CategoryName) values ('PETS#974');
insert into Category (CategoryName) values ('TRAVEL#1');
insert into Category (CategoryName) values ('FOOD - SNACKS#658');
insert into Category (CategoryName) values ('FOOD - BAKERY#202');
insert into Category (CategoryName) values ('FOOD - CONDIMENTS#815');
insert into Category (CategoryName) values ('OUTDOOR#407');
insert into Category (CategoryName) values ('FOOD - SNACKS#792');
insert into Category (CategoryName) values ('FOOD - BREAKFAST#670');
insert into Category (CategoryName) values ('PHOTOGRAPHY#414');
insert into Category (CategoryName) values ('KITCHEN#345');
insert into Category (CategoryName) values ('KITCHEN#664');
insert into Category (CategoryName) values ('ELECTRONICS#397');
insert into Category (CategoryName) values ('ART SUPPLIES#937');
insert into Category (CategoryName) values ('ACCESSORIES#292');
insert into Category (CategoryName) values ('FOOD - SNACKS#103');
insert into Category (CategoryName) values ('PETS#126');
insert into Category (CategoryName) values ('KITCHEN#167');
insert into Category (CategoryName) values ('FOOD - FREEZER#590');
insert into Category (CategoryName) values ('HEALTH#460');
insert into Category (CategoryName) values ('HOME#829');
insert into Category (CategoryName) values ('FOOD - DIPS#791');
insert into Category (CategoryName) values ('FOOD - BAKING#800');
insert into Category (CategoryName) values ('FOOD - GRAINS#91');
insert into Category (CategoryName) values ('FOOD - PREPARED FOODS#569');
insert into Category (CategoryName) values ('CRAFTS#201');
insert into Category (CategoryName) values ('OUTDOOR#924');
insert into Category (CategoryName) values ('FOOD - BAKING#967');
insert into Category (CategoryName) values ('FOOD - CEREAL#162');
insert into Category (CategoryName) values ('FOOD - BAKERY#615');
insert into Category (CategoryName) values ('CLOTHING - OUTERWEAR#279');
insert into Category (CategoryName) values ('ACCESSORIES#520');
insert into Category (CategoryName) values ('FOOD - CONDIMENTS#209');
insert into Category (CategoryName) values ('CLOTHING - FOOTWEAR#72');
insert into Category (CategoryName) values ('FOOD - SNACKS#761');
insert into Category (CategoryName) values ('FOOD - SNACKS#783');
insert into Category (CategoryName) values ('FOOD - BAKING#28');
insert into Category (CategoryName) values ('CLOTHING - SHIRTS#815');
insert into Category (CategoryName) values ('OUTDOOR#710');
insert into Category (CategoryName) values ('FOOD - SOUPS#489');
insert into Category (CategoryName) values ('FOOD - CONDIMENTS#344');
insert into Category (CategoryName) values ('FOOD - BEVERAGES#166');
insert into Category (CategoryName) values ('PHOTOGRAPHY#356');
insert into Category (CategoryName) values ('FOOD - FROZEN FOODS#692');
insert into Category (CategoryName) values ('CLOTHING - ACCESSORIES#640');
insert into Category (CategoryName) values ('HOME#216');
insert into Category (CategoryName) values ('PHOTOGRAPHY#843');
insert into Category (CategoryName) values ('KITCHEN#924');
insert into Category (CategoryName) values ('FOOD - BAKERY#701');
insert into Category (CategoryName) values ('ACCESSORIES#170');
insert into Category (CategoryName) values ('FOOD - SIDES#505');
insert into Category (CategoryName) values ('HEALTH#241');
insert into Category (CategoryName) values ('ELECTRONICS#62');
insert into Category (CategoryName) values ('FOOD - SAUCES#591');
insert into Category (CategoryName) values ('FOOD - CONFECTIONERY#288');
insert into Category (CategoryName) values ('FOOD - SNACKS#289');
insert into Category (CategoryName) values ('FOOD - BREAKFAST#731');
insert into Category (CategoryName) values ('KITCHEN#566');
insert into Category (CategoryName) values ('FOOD - GRAINS#70');
insert into Category (CategoryName) values ('ELECTRONICS#591');
insert into Category (CategoryName) values ('FOOD - FROZEN MEALS#428');
insert into Category (CategoryName) values ('OUTDOOR#651');
insert into Category (CategoryName) values ('FOOD - PREPARED FOODS#163');
insert into Category (CategoryName) values ('HOME#827');
insert into Category (CategoryName) values ('FOOD - FROZEN DESSERTS#9');
insert into Category (CategoryName) values ('FOOD - BEVERAGES#1000');
insert into Category (CategoryName) values ('OUTDOOR#895');
insert into Category (CategoryName) values ('HOME#192');
insert into Category (CategoryName) values ('FOOD - SEAFOOD#811');
insert into Category (CategoryName) values ('OUTDOOR#948');
insert into Category (CategoryName) values ('CLOTHING - ACCESSORIES#872');
insert into Category (CategoryName) values ('OUTDOOR#320');
insert into Category (CategoryName) values ('KITCHEN#950');
insert into Category (CategoryName) values ('OUTDOOR#433');
insert into Category (CategoryName) values ('GARDEN#957');
insert into Category (CategoryName) values ('CRAFTS#8');
insert into Category (CategoryName) values ('PETS#972');
insert into Category (CategoryName) values ('ELECTRONICS#685');
insert into Category (CategoryName) values ('HEALTH#98');
insert into Category (CategoryName) values ('CLOTHING - BOTTOMS#702');
insert into Category (CategoryName) values ('FOOD - FROZEN FOODS#408');
insert into Category (CategoryName) values ('FOOD - SALADS#623');
insert into Category (CategoryName) values ('FOOD - CONDIMENTS#838');
insert into Category (CategoryName) values ('PETS#168');
insert into Category (CategoryName) values ('KITCHEN#883');
insert into Category (CategoryName) values ('FOOD - MEAT#855');
insert into Category (CategoryName) values ('FOOD - MEAT#626');
insert into Category (CategoryName) values ('TOYS#848');
insert into Category (CategoryName) values ('FOOD - VEGETABLES#468');
insert into Category (CategoryName) values ('ELECTRONICS#245');
